### ISSUE TITLE
Pictures not saving

### ISSUE THREAD

**Issue by kelvinmwenda9** [habibmhamadi/blogapp-laravel-api#2]
Hey bro, went through your laravel android tutorial and was able to install project on my server for testing, however I am not able to create a new post once logged in. 

W/System.err: com.android.volley.TimeoutError
W/System.err:     at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:173)
W/System.err:     at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
W/System.err:     at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

**Comment by habibmhamadi** [comment]
@kelvinmwenda9 Make sure your Laravel server is running and you have the correct URL in your Android app. and also check if you have added internet permission and clearTextTraffic = true inside your Manifest file. if still faced the same problem then try uninstalling and reinstalling the app.

**Comment by kelvinmwenda9** [comment]
@habibmhamadi I've tried your solution but the post creation process issue still persists - here's the full 500 error displayed with my apis 

```
D/Volley: [31054] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] http://sub.adventsoko.co.ke/api/posts/create 0xe8e26b4 NORMAL 1> [lifetime=34908], [size=630], [rc=413], [retryCount=1]
E/Volley: [31054] BasicNetwork.performRequest: Unexpected response code 413 for http://sub.adventsoko.co.ke/api/posts/create
W/System.err: com.android.volley.ClientError
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199)
W/System.err:     at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
```


**Manifest**
```

> 
> <?xml version="1.0" encoding="utf-8"?>
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>     package="com.habib.blogapp">
> 
>     <uses-permission android:name="android.permission.INTERNET" />
> 
>     <application
>         android:allowBackup="true"
>         android:icon="@mipmap/ic_launcher"
>         android:label="@string/app_name"
>         android:roundIcon="@mipmap/ic_launcher_round"
>         android:supportsRtl="true"
>         android:theme="@style/AppTheme"
>         android:usesCleartextTraffic="true">
>         <activity android:name=".EditUserInfoActivity"></activity>
>         <activity android:name=".CommentActivity" />
>         <activity android:name=".EditPostActivity" />
>         <activity android:name=".AddPostActivity" />
>         <activity android:name=".HomeActivity" />
>         <activity android:name=".UserInfoActivity" />
>         <activity android:name=".AuthActivity" />
>         <activity android:name=".OnBoardActivity" />
>         <activity android:name=".MainActivity">
>             <intent-filter>
>                 <action android:name="android.intent.action.MAIN" />
> 
>                 <category android:name="android.intent.category.LAUNCHER" />
>             </intent-filter>
>         </activity>
>     </application>
> 
> </manifest>

```

**Comment by kelvinmwenda9** [comment]
```

> I/System.out: [OkHttp] sendRequest<<
> E/Volley: [31061] BasicNetwork.performRequest: Unexpected response code 500 for http://sub.adventsoko.co.ke/api/posts/create
> W/System.err: com.android.volley.ServerError
> W/System.err:     at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:205)
>         at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
>         at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
> W/System.err:     at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
> D/Surface: Surface::disconnect(this=0xccb79000,api=1)
> D/View: [Warning] assignParent to null: this = DecorView@b8766f5[AddPostActivity]
> I/InputTransport: Destroy ARC handle: 0xccdd0120

```

**Comment by habibmhamadi** [comment]
> @habibmhamadi I've tried your solution but the post creation process issue still persists - here's the full 500 error displayed with my apis
> 
> ```
> D/Volley: [31054] BasicNetwork.logSlowRequests: HTTP response for request=<[ ] http://sub.adventsoko.co.ke/api/posts/create 0xe8e26b4 NORMAL 1> [lifetime=34908], [size=630], [rc=413], [retryCount=1]
> E/Volley: [31054] BasicNetwork.performRequest: Unexpected response code 413 for http://sub.adventsoko.co.ke/api/posts/create
> W/System.err: com.android.volley.ClientError
>         at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199)
> W/System.err:     at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
>         at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
>         at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
> ```
> 
> **Manifest**
> 
> ```
> 
> > 
> > <?xml version="1.0" encoding="utf-8"?>
> > <manifest xmlns:android="http://schemas.android.com/apk/res/android"
> >     package="com.habib.blogapp">
> > 
> >     <uses-permission android:name="android.permission.INTERNET" />
> > 
> >     <application
> >         android:allowBackup="true"
> >         android:icon="@mipmap/ic_launcher"
> >         android:label="@string/app_name"
> >         android:roundIcon="@mipmap/ic_launcher_round"
> >         android:supportsRtl="true"
> >         android:theme="@style/AppTheme"
> >         android:usesCleartextTraffic="true">
> >         <activity android:name=".EditUserInfoActivity"></activity>
> >         <activity android:name=".CommentActivity" />
> >         <activity android:name=".EditPostActivity" />
> >         <activity android:name=".AddPostActivity" />
> >         <activity android:name=".HomeActivity" />
> >         <activity android:name=".UserInfoActivity" />
> >         <activity android:name=".AuthActivity" />
> >         <activity android:name=".OnBoardActivity" />
> >         <activity android:name=".MainActivity">
> >             <intent-filter>
> >                 <action android:name="android.intent.action.MAIN" />
> > 
> >                 <category android:name="android.intent.category.LAUNCHER" />
> >             </intent-filter>
> >         </activity>
> >     </application>
> > 
> > </manifest>
> ```

Response code 413. It means your request size is too large. I think you are trying to upload a large image. please try with images less than 1MB.

**Comment by habibmhamadi** [comment]
> assignParent to null: this = DecorView

And for code 500. there is some problem with your backend. or may you have some issue in volley implementation or even android view. please review your backend code and also in android also check if you passed some null values to volley params or layout.

**Comment by habibmhamadi** [comment]
Closing this issue because it is a framework limitation, not an issue.
